document.addEventListener("DOMContentLoaded", () => {
    const langData = {
            "en": {
                "nav-home": "Home",
                "nav-about": "About Me",
                "nav-offers": "Our Offers",
                "nav-recommendation": "Recommendation",
                "nav-contact": "Contact",
                "about-experience-text": "With over 35 years of experience in the industry, Dipl.-Ing. Dr. Gernot Mevec is a renowned engineer and scientist specializing in the development and application of high-performance materials.",
                "about-experience-text-btn":"Contact Us for More Info",
                "footer-name": "Dipl.-Ing. Dr. Gernot Mevec",
                "footer-title": "Engineering Office for Material Science",
                "footer-address": "Mühlbergweg 6",
                "footer-location": "4360 Grein, Austria/Europe",
                "footer-phone": "Telefon: +43 (660) 48 00 433",
                "footer-email-label": "E-Mail:",
                "footer-email": "contact@mevec.net",
                "footer-gisa": "GISA-Nr: 32433289",
                "footer-vat": "VAT Nr.: ATU40878207",
                "footer-privacy": "Privacy Policy",
                "rec-consultation-title": "Consultation and support in material development and damage cases",
                "rec-consultation-text": "We offer expert consultation in material development and damage analysis, tailored to ensure the optimal performance and longevity of your products. Our experienced team thoroughly examines your material needs, identifies suitable materials, and offers detailed insights to help you make informed decisions. We specialize in troubleshooting material-related issues, analyzing damage, and providing actionable solutions designed to minimize downtime, reduce maintenance costs, and enhance overall product durability. By partnering with us, you gain access to cutting-edge expertise and a commitment to material excellence that drives reliability, efficiency, and long-term success. Let us help you achieve superior performance and product lifespan with our specialized services.",
                "rec-research-title": "Research and Innovation Projects for Companies",
                "rec-research-text": "Transform your business with our tailored research and innovation projects, designed to meet your unique challenges and goals. We work closely with companies across various industries to develop cutting-edge solutions that not only drive growth but also enhance your competitive edge in the market. Our expert team is dedicated to exploring and integrating the latest technologies and methodologies, focusing on improving product performance, efficiency, and sustainability. Whether you're looking to optimize existing products or pioneer new innovations, our collaborative approach ensures that you stay ahead of the curve, positioning your business for long-term success and industry leadership.",
                "rec-support-title": "Customer Support and Technical Assistance in the Application of New Materials",
                "rec-support-text": "We are here to provide expert guidance on the application of new materials, ensuring that your operations run smoothly and efficiently. We work closely with you to guarantee optimal material performance, compliance with industry standards, and the successful integration of new materials into your processes. Whether you have questions about material properties, application techniques, or best practices, our team is ready to provide clear, actionable solutions. Count on us for prompt, reliable assistance that empowers your success and helps you achieve the highest standards in quality and performance.",
                "rec-training-title": "Training and Further Education for Companies and Educational Institutions",
                "rec-training-text": "Enhance your team’s capabilities and expertise with our specialized training programs, designed for both companies and educational institutions. Our comprehensive courses cover the latest advancements in materials science, cutting-edge technologies, and industry best practices, ensuring that your workforce stays ahead of the curve. We focus on fostering a culture of continuous learning, innovation, and practical problem-solving skills, empowering your team to address today’s challenges and prepare for tomorrow’s opportunities. Equip your employees, students, and research teams with the knowledge and tools they need to excel in a rapidly evolving field and drive long-term success within your organization.",
                "contact-header": "Contact",
                "contact-description": "Are you looking for an experienced expert in material development and innovative solutions? Contact Dipl.-Ing. Dr. Gernot Mevec and benefit from his extensive knowledge and international experience.",
                "contact-name-label": "Name",
                "contact-company-label": "Company Name",
                "contact-email-label": "E-Mail",
                "contact-subject-label": "Subject",
                "contact-message-label": "Message",
                "contact-send-button": "Send",
                "contact-privacy": "Privacy: Your information will only be used to respond to this request. We will never use this data for any other purposes. For more information, please see our",
                "contact-privacy-policy": "Privacy Policy",
                "rec-tuwien": "Technical University Vienna",
                "rec-tuwien-description": "The Vienna University of Technology offers a diverse range of over 50 bachelor's and master's programs in engineering, computer science, architecture, natural sciences, and business. Emphasizing interdisciplinary approaches and practical training, the university provides access to modern research facilities and a strong network of international partners for exchange opportunities. TU Wien is an excellent choice for a top-notch technical education.",
                "rec-tuclausthal": "Technical University Clausthal",
                "rec-tuclausthal-description": "The TU Clausthal is well-regarded for its exceptional academic programs and strong emphasis on research and innovation. Known for its specialized courses in engineering, natural sciences, and business, the university offers a dynamic learning environment with close student-faculty interactions. With a focus on practical skills and interdisciplinary collaboration, TU Clausthal prepares students for success in both academic and professional fields. The picturesque town of Clausthal-Zellerfeld, combined with the university's modern campus, provides an inspiring backdrop for both personal and academic development.",
                "rec-unileoben": "Montanuniversität Leoben",
                "rec-unileoben-description": "The University of Leoben, officially known as Montanuniversität Leoben, is highly regarded for its specialized academic programs and dedication to fostering innovation. Renowned for its excellence in engineering, natural resources, and material sciences, the university is a hub for cutting-edge research and industry collaboration. With a distinguished faculty and a student-centered approach, it offers a supportive and inspiring environment for learning. Additionally, its scenic location in the heart of Austria, combined with a vibrant student community and a strong focus on sustainability, provides an ideal setting for both academic achievement and personal development.",
                "rec-sheffield": "University of Sheffield",
                "rec-sheffield-description": "The University of Sheffield is highly regarded for its distinguished academic programs and commitment to student development. Renowned for its rigorous research initiatives and highly qualified faculty, the university provides a supportive and engaging learning environment. Additionally, the vibrant campus and the rich cultural offerings of the city create an ideal setting for academic and personal growth.",
                "rec-jku": "Johannes Kepler University Linz",
                "rec-jku-description": "The Johannes Kepler University Linz (JKU) is highly regarded for its innovative academic programs and strong focus on student success. Renowned for its cutting-edge research initiatives and distinguished faculty, the university fosters an inspiring and dynamic learning environment. Additionally, the modern campus, set against the picturesque backdrop of Linz, and the city's rich cultural and technological landscape provide an excellent foundation for both academic achievement and personal development.",
                "rec-rwth": "RWTH Aachen University",
                "rec-rwth-description": "RWTH Aachen University is renowned for its excellence in engineering, technology, and natural sciences. With a strong focus on research and innovation, the university offers a challenging academic environment. Its close ties with industry and cutting-edge facilities provide students with valuable hands-on experience, preparing them for successful careers. The vibrant city of Aachen adds to the dynamic atmosphere, offering both academic and cultural opportunities.",
                "privacy-title": "Privacy Policy",
                "privacy-text": "The protection of your personal data is of great concern to us. With this Privacy Policy, we would like to inform you about how we collect, process, and store your personal data. We strictly adhere to the applicable data protection laws, in particular the General Data Protection Regulation (GDPR) and the Austrian Data Protection Act (DSG).",
                "privacy-responsible-title": "1. Responsible Party",
                "privacy-responsible-text": "The party responsible for the processing of your personal data is:",
                "privacy-responsible": "DR GERNOT MEVEC CONSULTING<br>Mühlbergweg 6 4360 Grein AustriaE-Mail: contact@mevec.net<br>Phone: +43 (660) 48 00 433",
                "privacy-collection-title": "2. Collection and Processing of Personal Data",
                "privacy-collection-text": "We collect and process your personal data only if you voluntarily provide it to us, for example, by contacting us via our contact form, by e-mail, or when using our services.",
                "privacy-data-types": "The personal data we collect includes:",
                "privacy-contact-data": "Contact Data: Name, Company Name, Address, E-Mail Address, Phone Number",
                "privacy-communication-data": "Communication Data: Content of inquiries, e-mails, and correspondence",
                "privacy-contract-data": "Contract Data: Information about completed or planned projects, orders, or services",
                "privacy-payment-data": "Payment Data: Bank details and billing information (if necessary)",
                "privacy-purpose-title": "3. Purpose of Data Processing",
                "privacy-purpose-text": "The personal data we collect is processed for the following purposes:",
                "privacy-processing-inquiries": "Processing and responding to inquiries",
                "privacy-providing-services": "Providing our engineering services",
                "privacy-contracts-payments": "Executing contracts and processing payments",
                "privacy-communication": "Communication with you regarding our services and projects",
                "privacy-legal-obligations": "Complying with legal obligations, such as retaining business data for tax purposes",
                "privacy-legal-ground-title": "4. Legal Basis for Processing",
                "privacy-legal-ground-text": "The processing of your personal data is based on the following legal grounds:",
                "privacy-legal-contract": "Contract Fulfillment (Art. 6(1)(b) GDPR): Processing is necessary to fulfill our contractual obligations to you.",
                "privacy-consent": "Consent (Art. 6(1)(a) GDPR): If you give us your consent to process your data, for example when subscribing to a newsletter.",
                "privacy-legal-obligation": "Legal Obligation (Art. 6(1)(c) GDPR): We process data to comply with legal obligations, such as tax retention requirements.",
                "privacy-legitimate-interests": "Legitimate Interests (Art. 6(1)(f) GDPR): Processing may also be based on legitimate interests, such as ensuring the security of our IT infrastructure.",
                "privacy-data-sharing-title": "5. Data Sharing",
                "privacy-sharing-text": "We only share your personal data with third parties when this is necessary for the fulfillment of the above-mentioned purposes or when required by law. This includes:",
                "privacy-service-providers": "Service Providers: We use external service providers (e.g., IT service providers, accountants) who act on our behalf and with whom we have concluded data protection agreements.",
                "privacy-authorities": "Authorities: When required by law.",
                "privacy-third-country": "Your personal data may only be transferred to a third country outside the EU or EEA if this is necessary for the execution of a contract or due to legal obligations.",
                "privacy-data-storage-title": "6. Storage Duration",
                "privacy-storage-duration": "Your personal data will only be stored as long as necessary for the fulfillment of the above-mentioned purposes or as long as we are legally required to do so (e.g., for tax retention purposes). After that, your data will be deleted unless other legal obligations require retention.",
                "privacy-rights-title": "7. Your Rights as a Data Subject",
                "privacy-rights-text": "Under applicable data protection laws, you have various rights regarding your personal data:",
                "privacy-right-access": "Right to Access",
                "privacy-right-correction": "Right to Rectification",
                "privacy-right-deletion": "Right to Deletion",
                "privacy-right-restriction": "Right to Restriction of Processing",
                "privacy-right-portability": "Right to Data Portability",
                "privacy-right-objection": "Right to Object",
                "privacy-security-title": "8. Data Processing Security",
                "privacy-security-text": "We take appropriate technical and organizational measures to protect your personal data from unauthorized access, loss, or destruction. This includes data encryption, firewalls, and access controls.",
                "privacy-changes-title": "9. Changes to the Privacy Policy",
                "privacy-changes-text": "We reserve the right to update this privacy policy from time to time to reflect changes in our services or legal requirements. The most current version will be published on our website.",
                "privacy-contact-title": "10. Contact",
                "privacy-contact-text": "If you have any questions or concerns about data protection, you can contact us at any time:",
                "privacy-contact-details": "DR GERNOT MEVEC CONSULTING Mühlbergweg 6 4360 Grein Austria E-Mail: contact@mevec.net Phone: +43 (660) 48 00 433",
                "contact-headline": "Contact",
                "contact-text": "Are you looking for an experienced expert in material development and innovative solutions? Contact Dipl.-Ing. Dr. Gernot Mevec and benefit from his extensive knowledge and international experience."
            },
            "de": {
                "nav-home": "Startseite",
                "nav-about": "Über mich",
                "nav-offers": "Unsere Angebote",
                "nav-recommendation": "Empfehlung",
                "nav-contact": "Kontakt",
                "about-experience-text": "Mit über 35 Jahren Erfahrung in der Industrie ist Dipl.-Ing. Dr. Gernot Mevec ein renommierter Ingenieur und Wissenschaftler, der sich auf die Entwicklung und Anwendung von Hochleistungsmaterialien spezialisiert hat.",
                "about-experience-text-btn":"Kontaktieren Sie uns für weitere Informationen.",
                "footer-name": "Dipl.-Ing. Dr. Gernot Mevec",
                "footer-title": "Ingenieurbüro für Materialwissenschaften",
                "footer-address": "Mühlbergweg 6",
                "footer-location": "4360 Grein, Österreich/Europa",
                "footer-phone": "Telefon: +43 (660) 48 00 433",
                "footer-email-label": "E-Mail:",
                "footer-email": "contact@mevec.net",
                "footer-gisa": "GISA-Nr: 32433289",
                "footer-vat": "UID Nr: ATU40878207",
                "footer-privacy": "Datenschutzrichtlinie",
                "rec-consultation-title": "Beratung und Unterstützung bei der Materialentwicklung und Schadensfällen",
                "rec-consultation-text": "Wir bieten fachkundige Beratung in der Materialentwicklung und Schadensanalyse, maßgeschneidert, um die optimale Leistung und Lebensdauer Ihrer Produkte sicherzustellen. Unser erfahrenes Team prüft gründlich Ihre Materialbedürfnisse, identifiziert geeignete Materialien und bietet detaillierte Einblicke, die Ihnen helfen, fundierte Entscheidungen zu treffen. Wir sind auf die Fehlerbehebung bei materialbezogenen Problemen, die Schadensanalyse und die Bereitstellung umsetzbarer Lösungen spezialisiert, die darauf ausgelegt sind, Ausfallzeiten zu minimieren, Wartungskosten zu senken und die Gesamtlebensdauer des Produkts zu verbessern. Mit einer Partnerschaft mit uns erhalten Sie Zugang zu modernstem Fachwissen und einem Engagement für Materialexzellenz, das Zuverlässigkeit, Effizienz und langfristigen Erfolg fördert. Lassen Sie uns Ihnen helfen, überlegene Leistung und Produktlebensdauer mit unseren spezialisierten Dienstleistungen zu erreichen.",
                "rec-research-title": "Forschungs- und Innovationsprojekte für Unternehmen",
                "rec-research-text": "Verwandeln Sie Ihr Unternehmen mit unseren maßgeschneiderten Forschungs- und Innovationsprojekten, die darauf ausgelegt sind, Ihre einzigartigen Herausforderungen und Ziele zu erfüllen. Wir arbeiten eng mit Unternehmen aus verschiedenen Branchen zusammen, um bahnbrechende Lösungen zu entwickeln, die nicht nur das Wachstum fördern, sondern auch Ihre Wettbewerbsfähigkeit auf dem Markt steigern. Unser Expertenteam ist darauf spezialisiert, die neuesten Technologien und Methoden zu erforschen und zu integrieren, mit dem Fokus auf die Verbesserung der Produktleistung, Effizienz und Nachhaltigkeit. Ob Sie bestehende Produkte optimieren oder neue Innovationen entwickeln möchten, unser kollaborativer Ansatz stellt sicher, dass Sie immer einen Schritt voraus sind, Ihr Unternehmen langfristig für Erfolg und Branchenführung positionieren.",
                "rec-support-title": "Kundensupport und technische Unterstützung bei der Anwendung neuer Materialien",
                "rec-support-text": "Wir bieten fachkundige Anleitung zur Anwendung neuer Materialien, damit Ihre Abläufe reibungslos und effizient laufen. Wir arbeiten eng mit Ihnen zusammen, um die optimale Materialleistung, die Einhaltung von Branchenstandards und die erfolgreiche Integration neuer Materialien in Ihre Prozesse sicherzustellen. Ob Sie Fragen zu Materialeigenschaften, Anwendungstechniken oder Best Practices haben, unser Team ist bereit, klare, umsetzbare Lösungen zu liefern. Vertrauen Sie auf uns für schnelle, zuverlässige Unterstützung, die Ihren Erfolg stärkt und Ihnen hilft, höchste Standards in Qualität und Leistung zu erreichen.",
                "rec-training-title": "Schulungen und Weiterbildungen für Unternehmen und Bildungseinrichtungen",
                "rec-training-text": "Steigern Sie die Fähigkeiten und Expertise Ihres Teams mit unseren spezialisierten Schulungsprogrammen, die sowohl für Unternehmen als auch für Bildungseinrichtungen konzipiert sind. Unsere umfassenden Kurse decken die neuesten Entwicklungen in der Materialwissenschaft, moderne Technologien und Branchenbest Practices ab und sorgen dafür, dass Ihr Team immer einen Schritt voraus ist. Wir konzentrieren uns auf die Förderung einer Kultur des kontinuierlichen Lernens, der Innovation und praktischer Problemlösungsfähigkeiten, damit Ihr Team die Herausforderungen von heute meistern und sich auf die Chancen von morgen vorbereiten kann. Rüsten Sie Ihre Mitarbeiter, Studenten und Forschungsteams mit dem Wissen und den Werkzeugen aus, die sie benötigen, um in einem sich schnell entwickelnden Bereich erfolgreich zu sein und langfristigen Erfolg in Ihrer Organisation zu fördern.",
                "contact-header": "Kontakt",
                "contact-description": "Suchen Sie einen erfahrenen Experten für Materialentwicklung und innovative Lösungen? Kontaktieren Sie Dipl.-Ing. Dr. Gernot Mevec und profitieren Sie von seinem umfangreichen Wissen und internationalen Erfahrungen.",
                "contact-name-label": "Name",
                "contact-company-label": "Firmenname",
                "contact-email-label": "E-Mail",
                "contact-subject-label": "Betreff",
                "contact-message-label": "Nachricht",
                "contact-send-button": "Senden",
                "contact-privacy": "Datenschutz: Ihre Informationen werden nur verwendet, um auf diese Anfrage zu antworten. Wir werden diese Daten niemals für andere Zwecke verwenden. Weitere Informationen finden Sie in unserer",
                "contact-privacy-policy": "Datenschutzerklärung",
                "rec-tuwien": "Technische Universität Wien",
                "rec-tuwien-description": "Die Technische Universität Wien bietet eine breite Palette von mehr als 50 Bachelor- und Masterprogrammen in den Bereichen Ingenieurwesen, Informatik, Architektur, Naturwissenschaften und Wirtschaft. Mit interdisziplinären Ansätzen und praxisorientierter Ausbildung ermöglicht die Universität Zugang zu modernen Forschungseinrichtungen und einem starken internationalen Netzwerk für Austauschmöglichkeiten. Die TU Wien ist eine ausgezeichnete Wahl für eine erstklassige technische Ausbildung.",
                "rec-tuclausthal": "Technische Universität Clausthal",
                "rec-tuclausthal-description": "Die TU Clausthal ist bekannt für ihre hervorragenden akademischen Programme und ihre starke Betonung von Forschung und Innovation. Bekannt für ihre spezialisierten Kurse in den Bereichen Ingenieurwissenschaften, Naturwissenschaften und Wirtschaft bietet die Universität ein dynamisches Lernumfeld mit engen Interaktionen zwischen Studierenden und Dozenten. Mit einem Fokus auf praktische Fähigkeiten und interdisziplinäre Zusammenarbeit bereitet die TU Clausthal die Studierenden auf den Erfolg in akademischen und beruflichen Bereichen vor. Die malerische Stadt Clausthal-Zellerfeld, kombiniert mit dem modernen Campus der Universität, bietet einen inspirierenden Hintergrund für persönliche und akademische Entwicklung.",
                "rec-unileoben": "Montanuniversität Leoben",
                "rec-unileoben-description": "Die Universität Leoben, offiziell bekannt als Montanuniversität Leoben, ist hoch angesehen für ihre spezialisierten akademischen Programme und ihr Engagement für Innovation. Bekannt für ihre Exzellenz in den Bereichen Ingenieurwesen, natürliche Ressourcen und Materialwissenschaften, ist die Universität ein Zentrum für hochmoderne Forschung und Zusammenarbeit mit der Industrie. Mit einer renommierten Fakultät und einem studierendenzentrierten Ansatz bietet die Universität eine unterstützende und inspirierende Lernumgebung. Darüber hinaus bietet der malerische Standort im Herzen Österreichs, kombiniert mit einer lebendigen Studierendengemeinschaft und einem starken Fokus auf Nachhaltigkeit, ideale Voraussetzungen für akademischen Erfolg und persönliche Entwicklung.",
                "rec-sheffield": "University of Sheffield",
                "rec-sheffield-description": "Die University of Sheffield ist bekannt für ihre hervorragenden akademischen Programme und ihr Engagement für die Entwicklung der Studierenden. Die Universität bietet ein unterstützendes und anregendes Lernumfeld, das durch anspruchsvolle Forschungsinitiativen und hochqualifizierte Dozenten geprägt ist. Der lebendige Campus und die reichhaltige kulturelle Vielfalt der Stadt schaffen ideale Voraussetzungen für akademisches und persönliches Wachstum.",
                "rec-jku": "Johannes Kepler Universität Linz",
                "rec-jku-description": "Die Johannes Kepler Universität Linz (JKU) ist hoch angesehen für ihre innovativen akademischen Programme und ihre starke Ausrichtung auf den Erfolg der Studierenden. Bekannt für ihre cutting-edge Forschungsinitiativen und ihre renommierte Fakultät, fördert die Universität ein inspirierendes und dynamisches Lernumfeld. Der moderne Campus, eingebettet in die malerische Kulisse von Linz, und die kulturelle und technologische Landschaft der Stadt bieten ideale Bedingungen für akademischen Erfolg und persönliche Entwicklung.",
                "rec-rwth": "RWTH Aachen University",
                "rec-rwth-description": "Die RWTH Aachen University ist bekannt für ihre Exzellenz in Ingenieurwissenschaften, Technologie und Naturwissenschaften. Mit einem starken Fokus auf Forschung und Innovation bietet die Universität ein anspruchsvolles akademisches Umfeld. Enge Verbindungen zur Industrie und modernste Einrichtungen bieten den Studierenden wertvolle praktische Erfahrungen und bereiten sie auf eine erfolgreiche Karriere vor. Die lebendige Stadt Aachen trägt zur dynamischen Atmosphäre bei und bietet sowohl akademische als auch kulturelle Möglichkeiten.",
                "privacy-title": "Datenschutzerklärung",
                "privacy-text": "Der Schutz Ihrer persönlichen Daten ist uns ein wichtiges Anliegen. Mit dieser Datenschutzerklärung möchten wir Sie darüber informieren, wie wir Ihre personenbezogenen Daten erheben, verarbeiten und speichern. Wir halten uns dabei strikt an die geltenden Datenschutzgesetze, insbesondere an die Datenschutz-Grundverordnung (DSGVO) sowie das österreichische Datenschutzgesetz (DSG).",
                "privacy-responsible-title": "1. Verantwortlicher",
                "privacy-responsible-text": "Verantwortlicher für die Verarbeitung Ihrer personenbezogenen Daten ist:",
                "privacy-responsible": "DR GERNOT MEVEC CONSULTING<br>Mühlbergweg 6<br>4360 Grein Österreich<br>E-Mail: contact@mevec.net<br>Telefon: +43 (660) 48 00 433",
                "privacy-collection-title": "2. Erhebung und Verarbeitung personenbezogener Daten",
                "privacy-collection-text": "Wir erheben und verarbeiten Ihre personenbezogenen Daten nur, wenn Sie uns diese freiwillig zur Verfügung stellen, z.B. durch die Kontaktaufnahme über unser Kontaktformular, per E-Mail oder bei der Nutzung unserer Dienstleistungen.",
                "privacy-data-types": "Zu den personenbezogenen Daten, die wir erheben, gehören:",
                "privacy-contact-data": "Kontaktdaten: Name, Firmenname, Adresse, E-Mail-Adresse, Telefonnummer",
                "privacy-communication-data": "Kommunikationsdaten: Inhalte von Anfragen, E-Mails und Korrespondenzen",
                "privacy-contract-data": "Vertragsdaten: Informationen zu durchgeführten oder geplanten Projekten, Aufträgen oder Dienstleistungen",
                "privacy-payment-data": "Zahlungsdaten: Bankverbindung und Rechnungsdaten (bei Bedarf)",
                "privacy-purpose-title": "3. Zweck der Datenverarbeitung",
                "privacy-purpose-text": "Die von uns erhobenen personenbezogenen Daten werden zu folgenden Zwecken verarbeitet:",
                "privacy-processing-inquiries": "Bearbeitung und Beantwortung von Anfragen",
                "privacy-providing-services": "Erbringung unserer Ingenieurdienstleistungen",
                "privacy-contracts-payments": "Durchführung von Verträgen und Abwicklung von Zahlungen",
                "privacy-communication": "Kommunikation mit Ihnen über unsere Dienstleistungen und Projekte",
                "privacy-legal-obligations": "Erfüllung gesetzlicher Pflichten, wie z.B. die Aufbewahrung von Geschäftsdaten aus steuerrechtlichen Gründen",
                "privacy-legal-ground-title": "4. Rechtsgrundlage der Verarbeitung",
                "privacy-legal-ground-text": "Die Verarbeitung Ihrer personenbezogenen Daten erfolgt auf Grundlage der folgenden Rechtsgrundlagen:",
                "privacy-legal-contract": "Vertragserfüllung (Art. 6 Abs. 1 lit. b DSGVO): Die Verarbeitung erfolgt, um unsere vertraglichen Verpflichtungen Ihnen gegenüber zu erfüllen.",
                "privacy-consent": "Einwilligung (Art. 6 Abs. 1 lit. a DSGVO): Wenn Sie uns Ihre Einwilligung zur Verarbeitung Ihrer Daten geben, z.B. bei der Anmeldung zu einem Newsletter.",
                "privacy-legal-obligation": "Rechtliche Verpflichtung (Art. 6 Abs. 1 lit. c DSGVO): Wir verarbeiten Daten, um gesetzlichen Verpflichtungen nachzukommen, z.B. im Rahmen der steuerlichen Aufbewahrungspflichten.",
                "privacy-legitimate-interests": "Berechtigte Interessen (Art. 6 Abs. 1 lit. f DSGVO): Die Verarbeitung kann auch auf berechtigten Interessen beruhen, z.B. zur Wahrung der Sicherheit unserer IT-Infrastruktur.",
                "privacy-data-sharing-title": "5. Weitergabe von Daten",
                "privacy-sharing-text": "Wir geben Ihre personenbezogenen Daten nur an Dritte weiter, wenn dies zur Erfüllung der oben genannten Zwecke erforderlich ist oder wenn eine gesetzliche Verpflichtung besteht. Dazu gehören:",
                "privacy-service-providers": "Dienstleister: Wir setzen externe Dienstleister (z.B. IT-Dienstleister, Buchhalter) ein, die in unserem Auftrag tätig werden und mit denen wir entsprechende Datenschutzvereinbarungen geschlossen haben.",
                "privacy-authorities": "Behörden: Wenn dies zur Erfüllung gesetzlicher Verpflichtungen notwendig ist.",
                "privacy-third-country": "Eine Übermittlung Ihrer personenbezogenen Daten in ein Drittland außerhalb der EU oder des EWR erfolgt nur, wenn dies für die Durchführung eines Vertrages oder aufgrund gesetzlicher Bestimmungen erforderlich ist.",
                "privacy-data-storage-title": "6. Dauer der Speicherung",
                "privacy-storage-duration": "Ihre personenbezogenen Daten werden nur so lange gespeichert, wie es für die Erfüllung der oben genannten Zwecke erforderlich ist oder solange wir gesetzlich dazu verpflichtet sind (z.B. steuerliche Aufbewahrungspflichten). Danach werden Ihre Daten gelöscht, sofern keine anderen rechtlichen Verpflichtungen zur Aufbewahrung bestehen.",
                "privacy-rights-title": "7. Ihre Rechte als betroffene Person",
                "privacy-rights-text": "Im Rahmen der geltenden Datenschutzgesetze haben Sie verschiedene Rechte in Bezug auf Ihre personenbezogenen Daten:",
                "privacy-right-access": "Auskunftsrecht",
                "privacy-right-correction": "Recht auf Berichtigung",
                "privacy-right-deletion": "Recht auf Löschung",
                "privacy-right-restriction": "Recht auf Einschränkung der Verarbeitung",
                "privacy-right-portability": "Recht auf Datenübertragbarkeit",
                "privacy-right-objection": "Widerspruchsrecht",
                "privacy-security-title": "8. Sicherheit der Datenverarbeitung",
                "privacy-security-text": "Wir ergreifen angemessene technische und organisatorische Maßnahmen, um Ihre personenbezogenen Daten vor unbefugtem Zugriff, Verlust oder Zerstörung zu schützen. Dies umfasst unter anderem die Verschlüsselung von Daten und den Einsatz von Firewalls und Zugangskontrollen.",
                "privacy-changes-title": "9. Änderungen der Datenschutzerklärung",
                "privacy-changes-text": "Wir behalten uns vor, diese Datenschutzerklärung von Zeit zu Zeit zu aktualisieren, um Änderungen unserer Dienstleistungen oder gesetzlicher Anforderungen zu berücksichtigen. Die jeweils aktuelle Version wird auf unserer Website veröffentlicht.",
                "privacy-contact-title": "10. Kontakt",
                "privacy-contact-text": "Für Fragen oder Anliegen zum Thema Datenschutz können Sie sich jederzeit an uns wenden:",
                "privacy-contact-details": "DR GERNOT MEVEC CONSULTING<br>Mühlbergweg 6<br>4360 Grein Österreich<br>E-Mail: contact@mevec.net<br>Telefon: +43 (660) 48 00 433",
                "contact-text":"Suchen Sie einen erfahrenen Experten für Materialentwicklung und innovative Lösungen? Kontaktieren Sie Dipl.-Ing. Dr. Gernot Mevec und profitieren Sie von seinem umfangreichen Wissen und internationalen Erfahrungen.",
                "contact-headline": "Kontakt",
            }
    };
    const setLanguage = (language) => {
        const elementsToTranslate = document.querySelectorAll("[data-translate]");
        elementsToTranslate.forEach(el => {
            const key = el.getAttribute("data-translate");
            if (langData[language][key]) {
                el.textContent = langData[language][key];
            }
        });
    };

    let currentLanguage = localStorage.getItem("lang") || "en"; 
    setLanguage(currentLanguage);

    document.querySelector("a[href='?lang=en']").addEventListener("click", (e) => {
        e.preventDefault();
        setLanguage("en");
        localStorage.setItem("lang", "en"); 
        history.replaceState(null, null, "?lang=en"); 
    });

    document.querySelector("a[href='?lang=de']").addEventListener("click", (e) => {
        e.preventDefault();
        setLanguage("de");
        localStorage.setItem("lang", "de");
        history.replaceState(null, null, "?lang=de");
    });
});