document.addEventListener("DOMContentLoaded", () => {
    const langData = {
            "en": 
            {
                "nav-home": "Home",
                "nav-about": "About Me",
                "nav-offers": "Our Offers",
                "nav-recommendation": "Recommendation",
                "nav-contact": "Contact",
                "nav-gallery": "Gallery",
                "about-experience-text": "With over 35 years of experience in the industry, Dipl.-Ing. Dr. Gernot Mevec is a renowned engineer and scientist specializing in the development and application of high-performance materials.",
                "about-experience-text-btn":"Contact Us for More Info",
                "footer-name": "Dipl.-Ing. Dr. Gernot Mevec",
                "footer-title": "Engineering Office for Material Science",
                "footer-address": "Mühlbergweg 6",
                "footer-location": "4360 Grein, Austria/Europe",
                "footer-phone": "Telefon: +43 (660) 48 00 433",
                "footer-email-label": "E-Mail:",
                "footer-email": "contact@mevec.net",
                "footer-gisa": "GISA-Nr: 32433289",
                "footer-vat": "VAT Nr.: ATU40878207",
                "footer-privacy": "Privacy Policy",
                "footer-Created": "Created By",
                "rec-consultation-title": "Consultation and support in material development and damage cases",
                "rec-consultation-text": "We offer expert consultation in material development and damage analysis, tailored to ensure the optimal performance and longevity of your products. Our experienced team thoroughly examines your material needs, identifies suitable materials, and offers detailed insights to help you make informed decisions. We specialize in troubleshooting material-related issues, analyzing damage, and providing actionable solutions designed to minimize downtime, reduce maintenance costs, and enhance overall product durability. By partnering with us, you gain access to cutting-edge expertise and a commitment to material excellence that drives reliability, efficiency, and long-term success. Let us help you achieve superior performance and product lifespan with our specialized services.",
                "rec-research-title": "Research and Innovation Projects for Companies",
                "rec-research-text": "Transform your business with our tailored research and innovation projects, designed to meet your unique challenges and goals. We work closely with companies across various industries to develop cutting-edge solutions that not only drive growth but also enhance your competitive edge in the market. Our expert team is dedicated to exploring and integrating the latest technologies and methodologies, focusing on improving product performance, efficiency, and sustainability. Whether you're looking to optimize existing products or pioneer new innovations, our collaborative approach ensures that you stay ahead of the curve, positioning your business for long-term success and industry leadership.",
                "rec-support-title": "Customer Support and Technical Assistance in the Application of New Materials",
                "rec-support-text": "We are here to provide expert guidance on the application of new materials, ensuring that your operations run smoothly and efficiently. We work closely with you to guarantee optimal material performance, compliance with industry standards, and the successful integration of new materials into your processes. Whether you have questions about material properties, application techniques, or best practices, our team is ready to provide clear, actionable solutions. Count on us for prompt, reliable assistance that empowers your success and helps you achieve the highest standards in quality and performance.",
                "rec-training-title": "Training and Further Education for Companies and Educational Institutions",
                "rec-training-text": "Enhance your team’s capabilities and expertise with our specialized training programs, designed for both companies and educational institutions. Our comprehensive courses cover the latest advancements in materials science, cutting-edge technologies, and industry best practices, ensuring that your workforce stays ahead of the curve. We focus on fostering a culture of continuous learning, innovation, and practical problem-solving skills, empowering your team to address today’s challenges and prepare for tomorrow’s opportunities. Equip your employees, students, and research teams with the knowledge and tools they need to excel in a rapidly evolving field and drive long-term success within your organization.",
                "contact-header": "Contact",
                "contact-description": "Are you looking for an experienced expert in material development and innovative solutions? Contact Dipl.-Ing. Dr. Gernot Mevec and benefit from his extensive knowledge and international experience.",
                "contact-name-label": "Name",
                "contact-company-label": "Company Name",
                "contact-email-label": "E-Mail",
                "contact-subject-label": "Subject",
                "contact-message-label": "Message",
                "contact-send-button": "Send",
                "contact-privacy": "Privacy: Your information will only be used to respond to this request. We will never use this data for any other purposes. For more information, please see our",
                "contact-privacy-policy": "Privacy Policy",
                "rec-tuwien": "Technical University Vienna",
                "rec-tuwien-description": "The Vienna University of Technology offers a diverse range of over 50 bachelor's and master's programs in engineering, computer science, architecture, natural sciences, and business. Emphasizing interdisciplinary approaches and practical training, the university provides access to modern research facilities and a strong network of international partners for exchange opportunities. TU Wien is an excellent choice for a top-notch technical education.",
                "rec-tuclausthal": "Technical University Clausthal",
                "rec-tuclausthal-description": "The TU Clausthal is well-regarded for its exceptional academic programs and strong emphasis on research and innovation. Known for its specialized courses in engineering, natural sciences, and business, the university offers a dynamic learning environment with close student-faculty interactions. With a focus on practical skills and interdisciplinary collaboration, TU Clausthal prepares students for success in both academic and professional fields. The picturesque town of Clausthal-Zellerfeld, combined with the university's modern campus, provides an inspiring backdrop for both personal and academic development.",
                "rec-unileoben": "Montanuniversität Leoben",
                "rec-unileoben-description": "The University of Leoben, officially known as Montanuniversität Leoben, is highly regarded for its specialized academic programs and dedication to fostering innovation. Renowned for its excellence in engineering, natural resources, and material sciences, the university is a hub for cutting-edge research and industry collaboration. With a distinguished faculty and a student-centered approach, it offers a supportive and inspiring environment for learning. Additionally, its scenic location in the heart of Austria, combined with a vibrant student community and a strong focus on sustainability, provides an ideal setting for both academic achievement and personal development.",
                "rec-sheffield": "University of Sheffield",
                "rec-sheffield-description": "The University of Sheffield is highly regarded for its distinguished academic programs and commitment to student development. Renowned for its rigorous research initiatives and highly qualified faculty, the university provides a supportive and engaging learning environment. Additionally, the vibrant campus and the rich cultural offerings of the city create an ideal setting for academic and personal growth.",
                "rec-jku": "Johannes Kepler University Linz",
                "rec-jku-description": "The Johannes Kepler University Linz (JKU) is highly regarded for its innovative academic programs and strong focus on student success. Renowned for its cutting-edge research initiatives and distinguished faculty, the university fosters an inspiring and dynamic learning environment. Additionally, the modern campus, set against the picturesque backdrop of Linz, and the city's rich cultural and technological landscape provide an excellent foundation for both academic achievement and personal development.",
                "rec-rwth": "RWTH Aachen University",
                "rec-rwth-description": "RWTH Aachen University is renowned for its excellence in engineering, technology, and natural sciences. With a strong focus on research and innovation, the university offers a challenging academic environment. Its close ties with industry and cutting-edge facilities provide students with valuable hands-on experience, preparing them for successful careers. The vibrant city of Aachen adds to the dynamic atmosphere, offering both academic and cultural opportunities.",
                "privacy-title": "Privacy Policy",
                "privacy-text": "The protection of your personal data is of great concern to us. With this Privacy Policy, we would like to inform you about how we collect, process, and store your personal data. We strictly adhere to the applicable data protection laws, in particular the General Data Protection Regulation (GDPR) and the Austrian Data Protection Act (DSG).",
                "privacy-responsible-title": "1. Responsible Party",
                "privacy-responsible-text": "The party responsible for the processing of your personal data is:",
                "privacy-responsible": "DR GERNOT MEVEC CONSULTING<br>Mühlbergweg 6 4360 Grein AustriaE-Mail: contact@mevec.net<br>Phone: +43 (660) 48 00 433",
                "privacy-collection-title": "2. Collection and Processing of Personal Data",
                "privacy-collection-text": "We collect and process your personal data only if you voluntarily provide it to us, for example, by contacting us via our contact form, by e-mail, or when using our services.",
                "privacy-data-types": "The personal data we collect includes:",
                "privacy-contact-data": "Contact Data: Name, Company Name, Address, E-Mail Address, Phone Number",
                "privacy-communication-data": "Communication Data: Content of inquiries, e-mails, and correspondence",
                "privacy-contract-data": "Contract Data: Information about completed or planned projects, orders, or services",
                "privacy-payment-data": "Payment Data: Bank details and billing information (if necessary)",
                "privacy-purpose-title": "3. Purpose of Data Processing",
                "privacy-purpose-text": "The personal data we collect is processed for the following purposes:",
                "privacy-processing-inquiries": "Processing and responding to inquiries",
                "privacy-providing-services": "Providing our engineering services",
                "privacy-contracts-payments": "Executing contracts and processing payments",
                "privacy-communication": "Communication with you regarding our services and projects",
                "privacy-legal-obligations": "Complying with legal obligations, such as retaining business data for tax purposes",
                "privacy-legal-ground-title": "4. Legal Basis for Processing",
                "privacy-legal-ground-text": "The processing of your personal data is based on the following legal grounds:",
                "privacy-legal-contract": "Contract Fulfillment (Art. 6(1)(b) GDPR): Processing is necessary to fulfill our contractual obligations to you.",
                "privacy-consent": "Consent (Art. 6(1)(a) GDPR): If you give us your consent to process your data, for example when subscribing to a newsletter.",
                "privacy-legal-obligation": "Legal Obligation (Art. 6(1)(c) GDPR): We process data to comply with legal obligations, such as tax retention requirements.",
                "privacy-legitimate-interests": "Legitimate Interests (Art. 6(1)(f) GDPR): Processing may also be based on legitimate interests, such as ensuring the security of our IT infrastructure.",
                "privacy-data-sharing-title": "5. Data Sharing",
                "privacy-sharing-text": "We only share your personal data with third parties when this is necessary for the fulfillment of the above-mentioned purposes or when required by law. This includes:",
                "privacy-service-providers": "Service Providers: We use external service providers (e.g., IT service providers, accountants) who act on our behalf and with whom we have concluded data protection agreements.",
                "privacy-authorities": "Authorities: When required by law.",
                "privacy-third-country": "Your personal data may only be transferred to a third country outside the EU or EEA if this is necessary for the execution of a contract or due to legal obligations.",
                "privacy-data-storage-title": "6. Storage Duration",
                "privacy-storage-duration": "Your personal data will only be stored as long as necessary for the fulfillment of the above-mentioned purposes or as long as we are legally required to do so (e.g., for tax retention purposes). After that, your data will be deleted unless other legal obligations require retention.",
                "privacy-rights-title": "7. Your Rights as a Data Subject",
                "privacy-rights-text": "Under applicable data protection laws, you have various rights regarding your personal data:",
                "privacy-right-access": "Right to Access",
                "privacy-right-correction": "Right to Rectification",
                "privacy-right-deletion": "Right to Deletion",
                "privacy-right-restriction": "Right to Restriction of Processing",
                "privacy-right-portability": "Right to Data Portability",
                "privacy-right-objection": "Right to Object",
                "privacy-security-title": "8. Data Processing Security",
                "privacy-security-text": "We take appropriate technical and organizational measures to protect your personal data from unauthorized access, loss, or destruction. This includes data encryption, firewalls, and access controls.",
                "privacy-changes-title": "9. Changes to the Privacy Policy",
                "privacy-changes-text": "We reserve the right to update this privacy policy from time to time to reflect changes in our services or legal requirements. The most current version will be published on our website.",
                "privacy-contact-title": "10. Contact",
                "privacy-contact-text": "If you have any questions or concerns about data protection, you can contact us at any time:",
                "privacy-contact-details": "DR GERNOT MEVEC CONSULTING Mühlbergweg 6 4360 Grein Austria E-Mail: contact@mevec.net Phone: +43 (660) 48 00 433",
                "contact-headline": "Contact",
                "contact-text": "Are you looking for an experienced expert in material development and innovative solutions? Contact Dipl.-Ing. Dr. Gernot Mevec and benefit from his extensive knowledge and international experience.",
                "experience-title": "35 Years of Industry Experience",
                "experience-text": "Dr. Mevec boasts an impressive career in the industry, which has taken him through various positions and projects worldwide. His expertise in materials and material development has significantly contributed to innovation across numerous industries. His industrial career began in 1988 with the development of asbestos replacement materials. Just a year later, he took on the challenge of investigating a damage case caused by quartz jump. These two projects eventually led Dr. Mevec to focus his doctoral research on the development of high-temperature sol-gel fibers and the materials produced from them. This new group of materials found applications in many industries, including laboratory furnace construction, optical filament manufacturing, smartphone display glass, technical ceramics, electronic ceramics, and wafers. In the new millennium, his focus expanded to additional industries, particularly to support mats and thermal insulation for automotive catalytic converters and diesel particulate filters. Simultaneously, fibers and filaments were optimized for use in ceramic matrix composites (CMC) and metal matrix composites (MMC). Further developments led Dr. Mevec into the field of chemistry and petrochemistry, where he particularly addressed topics such as carbon black, chlorine reactors, Claus reactors, and the production of inorganic pigments. He also focused on the non-ferrous metals industry, particularly in the context of refractory materials. With 30 years of industry experience, Dr. Mevec founded his engineering office in 2020.",
                "teaching-title": "20 Years of Teaching Experience",
                "teaching-text": "In addition to his practical work in the industry, Dr. Mevec has taught at universities and technical colleges for over two decades. His experience as a lecturer encompasses the education of future engineers and technicians, contributing not only to the transfer of knowledge but also to the advancement of the technical field. Dr. Mevec has particularly focused on refractory materials technology at TU Vienna. At Montanuniversität Leoben, his emphasis was on high-temperature thermal insulation materials. International conferences and colloquia have taken Dr. Mevec around the globe. He has delivered lectures not only in Austria but also in Germany, Hungary, Poland, Romania, England, the USA, South Africa, India, Thailand, and China. In recent years, Dr. Mevec has also been teaching at an Austrian technical college (HTL), striving to pass on his extensive experience.",
                "research-title": "Research, Material Development, and Customer Support Worldwide",
                "research-text": "Dr. Mevec's work is distinguished by its international scope. He has led research projects and provided support across four continents, developing new materials and assisting clients in a wide range of industries. His global network and interdisciplinary projects establish him as an expert of the highest caliber. His approach always begins with listening to the customer and potential end-users, guided by the motto: 'Impossible is not an option.' Solutions to complex challenges often cannot be achieved merely by changing materials. Instead, one must consider the entire system and think creatively and constructively. In collaboration with renowned institutes and universities across Europe and the United States, new materials were developed and optimized for specific applications. Dr. Mevec has traveled professionally to over 70 countries, consulting for and supplying both small businesses and global corporations on-site.",
                "founding-title": "Founding of Engineering Firm",
                "founding-text": "In 2020, Dr. Mevec founded his own engineering consultancy with the goal of advising companies and organizations in the research, development, and application of materials. His extensive experience and ability to devise innovative solutions make him a sought-after consultant and partner for businesses worldwide. His current work focuses on refractory materials, inorganic fibers and filaments, glass production, and high-temperature recycling processes.",
                "faq-1": "What services does Mevec Consulting offer?",
                "faq-1-text": "Mevec Consulting specializes in material development and innovative solutions. We offer consultancy for material science, process optimization, and engineering solutions tailored to your project needs.",
                "faq-2": "How can I book a consultation with Dr. Gernot Mevec?",
                "faq-2-text": "You can book a consultation by filling out the contact form above, calling our office, or sending an email to contact@mevec.net. We’ll get back to you as soon as possible to arrange a meeting.",
                "faq-3": "How soon can I expect a response after contacting Mevec Consulting?",
                "faq-3-text": "We aim to respond to all inquiries within 2-3 business days. If your inquiry is urgent, please call us directly.",
                "faq-4": "Does Dr. Mevec and his team provide services only in Austria or also abroad?",
                "faq-4-text": "Dr. Mevec is well travelled and offers his services globally.",
                "faq-5": "Does Dr. Mevec offer analytical services within his company?",
                "faq-5-text": "The engineering office Dr. Gernot Mevec Consulting in Austria does not include a lab of its own. However, Dr. Mevec can direct you to the proper analytical labs or coordinate and manage the necessary analytical work for you.",
                "faq-6": "Does Dr. Mevec provide refractory engineering services?",
                "faq-6-text": "Dr. Mevec does not provide refractory engineering services. However, the office is well connected and can direct you to a proper independent service firm.",
                "faq-7": "Does Dr. Mevec provide support and service in case of refractory failure?",
                "faq-7-text": "A clear focus of the engineering services is refractory failure analyses. Refractory failure can be a very tricky subject. Often enough one can find very little evidence or proof, hence it is a detective job. A challenge for the team of Dr. Mevec.",
                "faq-8": "Once a problem occurs; what shall be the first steps on site?",
                "faq-8-text": "To solve the mystery of a refractory failure, one must act like a detective. The failure shall be well documented by means of photos and samples. Data shall be collected regarding temperatures, atmospheric pressures, pH, chemical composition, dust, etc.",
                "faq-9": "Where can I source raw materials (mostly inorganic)?",
                "faq-9-text": "The team around Dr. Mevec can provide you with information on where to source raw materials and get you in touch with possible suppliers.",
                "faq-10": "What refractory materials are available?",
                "faq-10-text": "High-temperature applications require several different refractory materials; castables, bricks, pre-shaped parts, insulation, seals, and gaskets, etc. Dr. Mevec and his team can guide you to find the right materials and suppliers.",
                "faq-11": "What technical ceramics are suitable for high-temperature applications?",
                "faq-11-text": "High-temperature applications not only require refractory material but also technical ceramics. Dr. Mevec and his team can guide you to find the right materials and suppliers.",
                "faq-12": "How can I prevent corrosion in high-temperature processes?",
                "faq-12-text": "High-temperature processes often result in corrosive gases and condensates. As a result, one must properly design the furnace shell to either operate above the dew point or well below the critical temperature of corrosion protection coating. Dr. Mevec and his team can guide you in the right direction.",
                "faq-13": "How can Dr. Mevec help with process design?",
                "faq-13-text": "Dr. Mevec and his team will help you to design a high-temperature process and monitor the relevant parameters. Tight and proper monitoring will help you to narrow the operating range and improve your performance and productivity.",
                "faq-14": "How can I optimize energy consumption?",
                "faq-14-text": "Energy is a key element of cost. Considering the high energy cost as well as the high cost fluctuation, one must understand that end-user requests for better insulation to reduce overall cost. However, improving insulation may reduce refractory life. A well-balanced system shall be designed. The team of Dr. Mevec is happy to help you find your optimum.",
                "faq-15": "How can I find the right OEM (Original Equipment Manufacturer)?",
                "faq-15-text": "Europe houses quite a number of well-established OEMs for almost any industry and application. Dr. Mevec and his team can guide you to find the right OEM for your application.",
                "faq-16": "What if Dr. Mevec's team cannot provide the needed service?",
                "faq-16-text": "If the team of Dr. Mevec cannot provide whatever you may need, we gladly refer you to other industrial experts within our network.",
                "created-head":"This Website was created by:",
                "created-text":"This website was created by Jakob Hintseiner and Daniel Macek as part of an Information Technology Project (ITP) at HTL Waidhofen an der Ybbs during the 2024/25 academic year. This project was a valuable opportunity for us to take the theoretical knowledge gained throughout our studies and apply it in a practical, real-world context. Our goal was to create a functional, user-friendly, and innovation. It would not have been possible without the support of those who believed in our vision and provided us with the opportunities to grow and succeed."
            },
            "de": 
            {
                "nav-home": "Startseite",
                "nav-about": "Über mich",
                "nav-offers": "Angebote",
                "nav-recommendation": "Empfehlung",
                "nav-contact": "Kontakt",
                "nav-gallery": "Galerie",
                "about-experience-text": "Mit über 35 Jahren Erfahrung in der Industrie ist Dipl.-Ing. Dr. Gernot Mevec ein renommierter Ingenieur und Wissenschaftler, der sich auf die Entwicklung und Anwendung von Hochleistungsmaterialien spezialisiert hat.",
                "about-experience-text-btn":"Kontaktieren Sie uns für weitere Informationen.",
                "footer-name": "Dipl.-Ing. Dr. Gernot Mevec",
                "footer-title": "Ingenieurbüro für Materialwissenschaften",
                "footer-address": "Mühlbergweg 6",
                "footer-location": "4360 Grein, Österreich/Europa",
                "footer-phone": "Telefon: +43 (660) 48 00 433",
                "footer-email-label": "E-Mail:",
                "footer-email": "contact@mevec.net",
                "footer-gisa": "GISA-Nr: 32433289",
                "footer-vat": "UID Nr: ATU40878207",
                "footer-privacy": "Datenschutzrichtlinie",
                "footer-Created": "Created by",
                "rec-consultation-title": "Beratung und Unterstützung bei der Materialentwicklung und Schadensfällen",
                "rec-consultation-text": "Wir bieten fachkundige Beratung in der Materialentwicklung und Schadensanalyse, maßgeschneidert, um die optimale Leistung und Lebensdauer Ihrer Produkte sicherzustellen. Unser erfahrenes Team prüft gründlich Ihre Materialbedürfnisse, identifiziert geeignete Materialien und bietet detaillierte Einblicke, die Ihnen helfen, fundierte Entscheidungen zu treffen. Wir sind auf die Fehlerbehebung bei materialbezogenen Problemen, die Schadensanalyse und die Bereitstellung umsetzbarer Lösungen spezialisiert, die darauf ausgelegt sind, Ausfallzeiten zu minimieren, Wartungskosten zu senken und die Gesamtlebensdauer des Produkts zu verbessern. Mit einer Partnerschaft mit uns erhalten Sie Zugang zu modernstem Fachwissen und einem Engagement für Materialexzellenz, das Zuverlässigkeit, Effizienz und langfristigen Erfolg fördert. Lassen Sie uns Ihnen helfen, überlegene Leistung und Produktlebensdauer mit unseren spezialisierten Dienstleistungen zu erreichen.",
                "rec-research-title": "Forschungs- und Innovationsprojekte für Unternehmen",
                "rec-research-text": "Verwandeln Sie Ihr Unternehmen mit unseren maßgeschneiderten Forschungs- und Innovationsprojekten, die darauf ausgelegt sind, Ihre einzigartigen Herausforderungen und Ziele zu erfüllen. Wir arbeiten eng mit Unternehmen aus verschiedenen Branchen zusammen, um bahnbrechende Lösungen zu entwickeln, die nicht nur das Wachstum fördern, sondern auch Ihre Wettbewerbsfähigkeit auf dem Markt steigern. Unser Expertenteam ist darauf spezialisiert, die neuesten Technologien und Methoden zu erforschen und zu integrieren, mit dem Fokus auf die Verbesserung der Produktleistung, Effizienz und Nachhaltigkeit. Ob Sie bestehende Produkte optimieren oder neue Innovationen entwickeln möchten, unser kollaborativer Ansatz stellt sicher, dass Sie immer einen Schritt voraus sind, Ihr Unternehmen langfristig für Erfolg und Branchenführung positionieren.",
                "rec-support-title": "Kundensupport und technische Unterstützung bei der Anwendung neuer Materialien",
                "rec-support-text": "Wir bieten fachkundige Anleitung zur Anwendung neuer Materialien, damit Ihre Abläufe reibungslos und effizient laufen. Wir arbeiten eng mit Ihnen zusammen, um die optimale Materialleistung, die Einhaltung von Branchenstandards und die erfolgreiche Integration neuer Materialien in Ihre Prozesse sicherzustellen. Ob Sie Fragen zu Materialeigenschaften, Anwendungstechniken oder Best Practices haben, unser Team ist bereit, klare, umsetzbare Lösungen zu liefern. Vertrauen Sie auf uns für schnelle, zuverlässige Unterstützung, die Ihren Erfolg stärkt und Ihnen hilft, höchste Standards in Qualität und Leistung zu erreichen.",
                "rec-training-title": "Schulungen und Weiterbildungen für Unternehmen und Bildungseinrichtungen",
                "rec-training-text": "Steigern Sie die Fähigkeiten und Expertise Ihres Teams mit unseren spezialisierten Schulungsprogrammen, die sowohl für Unternehmen als auch für Bildungseinrichtungen konzipiert sind. Unsere umfassenden Kurse decken die neuesten Entwicklungen in der Materialwissenschaft, moderne Technologien und Branchenbest Practices ab und sorgen dafür, dass Ihr Team immer einen Schritt voraus ist. Wir konzentrieren uns auf die Förderung einer Kultur des kontinuierlichen Lernens, der Innovation und praktischer Problemlösungsfähigkeiten, damit Ihr Team die Herausforderungen von heute meistern und sich auf die Chancen von morgen vorbereiten kann. Rüsten Sie Ihre Mitarbeiter, Studenten und Forschungsteams mit dem Wissen und den Werkzeugen aus, die sie benötigen, um in einem sich schnell entwickelnden Bereich erfolgreich zu sein und langfristigen Erfolg in Ihrer Organisation zu fördern.",
                "contact-header": "Kontakt",
                "contact-description": "Suchen Sie einen erfahrenen Experten für Materialentwicklung und innovative Lösungen? Kontaktieren Sie Dipl.-Ing. Dr. Gernot Mevec und profitieren Sie von seinem umfangreichen Wissen und internationalen Erfahrungen.",
                "contact-name-label": "Name",
                "contact-company-label": "Firmenname",
                "contact-email-label": "E-Mail",
                "contact-subject-label": "Betreff",
                "contact-message-label": "Nachricht",
                "contact-send-button": "Senden",
                "contact-privacy": "Datenschutz: Ihre Informationen werden nur verwendet, um auf diese Anfrage zu antworten. Wir werden diese Daten niemals für andere Zwecke verwenden. Weitere Informationen finden Sie in unserer",
                "contact-privacy-policy": "Datenschutzerklärung",
                "rec-tuwien": "Technische Universität Wien",
                "rec-tuwien-description": "Die Technische Universität Wien bietet eine breite Palette von mehr als 50 Bachelor- und Masterprogrammen in den Bereichen Ingenieurwesen, Informatik, Architektur, Naturwissenschaften und Wirtschaft. Mit interdisziplinären Ansätzen und praxisorientierter Ausbildung ermöglicht die Universität Zugang zu modernen Forschungseinrichtungen und einem starken internationalen Netzwerk für Austauschmöglichkeiten. Die TU Wien ist eine ausgezeichnete Wahl für eine erstklassige technische Ausbildung.",
                "rec-tuclausthal": "Technische Universität Clausthal",
                "rec-tuclausthal-description": "Die TU Clausthal ist bekannt für ihre hervorragenden akademischen Programme und ihre starke Betonung von Forschung und Innovation. Bekannt für ihre spezialisierten Kurse in den Bereichen Ingenieurwissenschaften, Naturwissenschaften und Wirtschaft bietet die Universität ein dynamisches Lernumfeld mit engen Interaktionen zwischen Studierenden und Dozenten. Mit einem Fokus auf praktische Fähigkeiten und interdisziplinäre Zusammenarbeit bereitet die TU Clausthal die Studierenden auf den Erfolg in akademischen und beruflichen Bereichen vor. Die malerische Stadt Clausthal-Zellerfeld, kombiniert mit dem modernen Campus der Universität, bietet einen inspirierenden Hintergrund für persönliche und akademische Entwicklung.",
                "rec-unileoben": "Montanuniversität Leoben",
                "rec-unileoben-description": "Die Universität Leoben, offiziell bekannt als Montanuniversität Leoben, ist hoch angesehen für ihre spezialisierten akademischen Programme und ihr Engagement für Innovation. Bekannt für ihre Exzellenz in den Bereichen Ingenieurwesen, natürliche Ressourcen und Materialwissenschaften, ist die Universität ein Zentrum für hochmoderne Forschung und Zusammenarbeit mit der Industrie. Mit einer renommierten Fakultät und einem studierendenzentrierten Ansatz bietet die Universität eine unterstützende und inspirierende Lernumgebung. Darüber hinaus bietet der malerische Standort im Herzen Österreichs, kombiniert mit einer lebendigen Studierendengemeinschaft und einem starken Fokus auf Nachhaltigkeit, ideale Voraussetzungen für akademischen Erfolg und persönliche Entwicklung.",
                "rec-sheffield": "University of Sheffield",
                "rec-sheffield-description": "Die University of Sheffield ist bekannt für ihre hervorragenden akademischen Programme und ihr Engagement für die Entwicklung der Studierenden. Die Universität bietet ein unterstützendes und anregendes Lernumfeld, das durch anspruchsvolle Forschungsinitiativen und hochqualifizierte Dozenten geprägt ist. Der lebendige Campus und die reichhaltige kulturelle Vielfalt der Stadt schaffen ideale Voraussetzungen für akademisches und persönliches Wachstum.",
                "rec-jku": "Johannes Kepler Universität Linz",
                "rec-jku-description": "Die Johannes Kepler Universität Linz (JKU) ist hoch angesehen für ihre innovativen akademischen Programme und ihre starke Ausrichtung auf den Erfolg der Studierenden. Bekannt für ihre cutting-edge Forschungsinitiativen und ihre renommierte Fakultät, fördert die Universität ein inspirierendes und dynamisches Lernumfeld. Der moderne Campus, eingebettet in die malerische Kulisse von Linz, und die kulturelle und technologische Landschaft der Stadt bieten ideale Bedingungen für akademischen Erfolg und persönliche Entwicklung.",
                "rec-rwth": "RWTH Aachen University",
                "rec-rwth-description": "Die RWTH Aachen University ist bekannt für ihre Exzellenz in Ingenieurwissenschaften, Technologie und Naturwissenschaften. Mit einem starken Fokus auf Forschung und Innovation bietet die Universität ein anspruchsvolles akademisches Umfeld. Enge Verbindungen zur Industrie und modernste Einrichtungen bieten den Studierenden wertvolle praktische Erfahrungen und bereiten sie auf eine erfolgreiche Karriere vor. Die lebendige Stadt Aachen trägt zur dynamischen Atmosphäre bei und bietet sowohl akademische als auch kulturelle Möglichkeiten.",
                "privacy-title": "Datenschutzerklärung",
                "privacy-text": "Der Schutz Ihrer persönlichen Daten ist uns ein wichtiges Anliegen. Mit dieser Datenschutzerklärung möchten wir Sie darüber informieren, wie wir Ihre personenbezogenen Daten erheben, verarbeiten und speichern. Wir halten uns dabei strikt an die geltenden Datenschutzgesetze, insbesondere an die Datenschutz-Grundverordnung (DSGVO) sowie das österreichische Datenschutzgesetz (DSG).",
                "privacy-responsible-title": "1. Verantwortlicher",
                "privacy-responsible-text": "Verantwortlicher für die Verarbeitung Ihrer personenbezogenen Daten ist:",
                "privacy-responsible": "DR GERNOT MEVEC CONSULTING<br>Mühlbergweg 6<br>4360 Grein Österreich<br>E-Mail: contact@mevec.net<br>Telefon: +43 (660) 48 00 433",
                "privacy-collection-title": "2. Erhebung und Verarbeitung personenbezogener Daten",
                "privacy-collection-text": "Wir erheben und verarbeiten Ihre personenbezogenen Daten nur, wenn Sie uns diese freiwillig zur Verfügung stellen, z.B. durch die Kontaktaufnahme über unser Kontaktformular, per E-Mail oder bei der Nutzung unserer Dienstleistungen.",
                "privacy-data-types": "Zu den personenbezogenen Daten, die wir erheben, gehören:",
                "privacy-contact-data": "Kontaktdaten: Name, Firmenname, Adresse, E-Mail-Adresse, Telefonnummer",
                "privacy-communication-data": "Kommunikationsdaten: Inhalte von Anfragen, E-Mails und Korrespondenzen",
                "privacy-contract-data": "Vertragsdaten: Informationen zu durchgeführten oder geplanten Projekten, Aufträgen oder Dienstleistungen",
                "privacy-payment-data": "Zahlungsdaten: Bankverbindung und Rechnungsdaten (bei Bedarf)",
                "privacy-purpose-title": "3. Zweck der Datenverarbeitung",
                "privacy-purpose-text": "Die von uns erhobenen personenbezogenen Daten werden zu folgenden Zwecken verarbeitet:",
                "privacy-processing-inquiries": "Bearbeitung und Beantwortung von Anfragen",
                "privacy-providing-services": "Erbringung unserer Ingenieurdienstleistungen",
                "privacy-contracts-payments": "Durchführung von Verträgen und Abwicklung von Zahlungen",
                "privacy-communication": "Kommunikation mit Ihnen über unsere Dienstleistungen und Projekte",
                "privacy-legal-obligations": "Erfüllung gesetzlicher Pflichten, wie z.B. die Aufbewahrung von Geschäftsdaten aus steuerrechtlichen Gründen",
                "privacy-legal-ground-title": "4. Rechtsgrundlage der Verarbeitung",
                "privacy-legal-ground-text": "Die Verarbeitung Ihrer personenbezogenen Daten erfolgt auf Grundlage der folgenden Rechtsgrundlagen:",
                "privacy-legal-contract": "Vertragserfüllung (Art. 6 Abs. 1 lit. b DSGVO): Die Verarbeitung erfolgt, um unsere vertraglichen Verpflichtungen Ihnen gegenüber zu erfüllen.",
                "privacy-consent": "Einwilligung (Art. 6 Abs. 1 lit. a DSGVO): Wenn Sie uns Ihre Einwilligung zur Verarbeitung Ihrer Daten geben, z.B. bei der Anmeldung zu einem Newsletter.",
                "privacy-legal-obligation": "Rechtliche Verpflichtung (Art. 6 Abs. 1 lit. c DSGVO): Wir verarbeiten Daten, um gesetzlichen Verpflichtungen nachzukommen, z.B. im Rahmen der steuerlichen Aufbewahrungspflichten.",
                "privacy-legitimate-interests": "Berechtigte Interessen (Art. 6 Abs. 1 lit. f DSGVO): Die Verarbeitung kann auch auf berechtigten Interessen beruhen, z.B. zur Wahrung der Sicherheit unserer IT-Infrastruktur.",
                "privacy-data-sharing-title": "5. Weitergabe von Daten",
                "privacy-sharing-text": "Wir geben Ihre personenbezogenen Daten nur an Dritte weiter, wenn dies zur Erfüllung der oben genannten Zwecke erforderlich ist oder wenn eine gesetzliche Verpflichtung besteht. Dazu gehören:",
                "privacy-service-providers": "Dienstleister: Wir setzen externe Dienstleister (z.B. IT-Dienstleister, Buchhalter) ein, die in unserem Auftrag tätig werden und mit denen wir entsprechende Datenschutzvereinbarungen geschlossen haben.",
                "privacy-authorities": "Behörden: Wenn dies zur Erfüllung gesetzlicher Verpflichtungen notwendig ist.",
                "privacy-third-country": "Eine Übermittlung Ihrer personenbezogenen Daten in ein Drittland außerhalb der EU oder des EWR erfolgt nur, wenn dies für die Durchführung eines Vertrages oder aufgrund gesetzlicher Bestimmungen erforderlich ist.",
                "privacy-data-storage-title": "6. Dauer der Speicherung",
                "privacy-storage-duration": "Ihre personenbezogenen Daten werden nur so lange gespeichert, wie es für die Erfüllung der oben genannten Zwecke erforderlich ist oder solange wir gesetzlich dazu verpflichtet sind (z.B. steuerliche Aufbewahrungspflichten). Danach werden Ihre Daten gelöscht, sofern keine anderen rechtlichen Verpflichtungen zur Aufbewahrung bestehen.",
                "privacy-rights-title": "7. Ihre Rechte als betroffene Person",
                "privacy-rights-text": "Im Rahmen der geltenden Datenschutzgesetze haben Sie verschiedene Rechte in Bezug auf Ihre personenbezogenen Daten:",
                "privacy-right-access": "Auskunftsrecht",
                "privacy-right-correction": "Recht auf Berichtigung",
                "privacy-right-deletion": "Recht auf Löschung",
                "privacy-right-restriction": "Recht auf Einschränkung der Verarbeitung",
                "privacy-right-portability": "Recht auf Datenübertragbarkeit",
                "privacy-right-objection": "Widerspruchsrecht",
                "privacy-security-title": "8. Sicherheit der Datenverarbeitung",
                "privacy-security-text": "Wir ergreifen angemessene technische und organisatorische Maßnahmen, um Ihre personenbezogenen Daten vor unbefugtem Zugriff, Verlust oder Zerstörung zu schützen. Dies umfasst unter anderem die Verschlüsselung von Daten und den Einsatz von Firewalls und Zugangskontrollen.",
                "privacy-changes-title": "9. Änderungen der Datenschutzerklärung",
                "privacy-changes-text": "Wir behalten uns vor, diese Datenschutzerklärung von Zeit zu Zeit zu aktualisieren, um Änderungen unserer Dienstleistungen oder gesetzlicher Anforderungen zu berücksichtigen. Die jeweils aktuelle Version wird auf unserer Website veröffentlicht.",
                "privacy-contact-title": "10. Kontakt",
                "privacy-contact-text": "Für Fragen oder Anliegen zum Thema Datenschutz können Sie sich jederzeit an uns wenden:",
                "privacy-contact-details": "DR GERNOT MEVEC CONSULTING<br>Mühlbergweg 6<br>4360 Grein Österreich<br>E-Mail: contact@mevec.net<br>Telefon: +43 (660) 48 00 433",
                "contact-text":"Suchen Sie einen erfahrenen Experten für Materialentwicklung und innovative Lösungen? Kontaktieren Sie Dipl.-Ing. Dr. Gernot Mevec und profitieren Sie von seinem umfangreichen Wissen und internationalen Erfahrungen.",
                "contact-headline": "Kontakt",
                "experience-title": "35 Jahre Branchenerfahrung",
                "experience-text": "Dr. Mevec kann auf eine beeindruckende Karriere in der Industrie zurückblicken, die ihn durch verschiedene Positionen und Projekte weltweit führte. Seine Expertise im Bereich Material und Materialentwicklung hat maßgeblich zur Innovation in zahlreichen Industrien beigetragen. Seine Industrietätigkeit begann im Jahr 1988 mit der Entwicklung von Asbestersatzstoffen. Bereits ein Jahr später stellt er sich der Herausforderung in einem Schadensfall zu ermitteln; ausgelöst durch den Quarzsprung. Diese beiden Projekte führen schließlich dazu, dass sich Dr. Mevec im Rahmen seiner Dissertation auf die Entwicklung von Hochtemperatur-Sol-Gel-Fasern und den daraus hergestellten Werkstoffen konzentrierte. Anwendung findet diese neue Werkstoffgruppe in vielen Branchen: Laborofenbau; Herstellung optischer Filamente, Handy-Display-Gläser, technische Keramik, Elektronik-Keramik, Wafer, etc. Im neuen Jahrtausend sollte der Focus auf weitere Branchen ausgedehnt werden und fiel auf Lagermatten und Wärmedämmung für KFZ-Katalysatoren und Dieselpartikelfilter. Parallel wurden Fasern und Filamente für den Einsatz in CMC und MMC optimiert. Die weitere Entwicklung führte Dr. Mevec in den Bereich Chemie und Petrochemie, wo er sich insbesondere mit den Themen Carbon Black, Chlorreaktoren, Claus Reaktoren Herstellung anorganischer Pigmente beschäftigte. Ebenso stand die NE-Metallindustrie im Fokus hinsichtlich feuerfester Werkstoffe. Mit 30 Jahren Branchenerfahrung hat Dr. Mevec im Jahr 2020 sein Ingenieurbüro gegründet. ",
                "teaching-title": "20 Jahre Lehrerfahrung",
                "teaching-text": "Neben seiner praktischen Arbeit in der Industrie hat Dr. Mevec über zwei Jahrzehnte an Universitäten und Fachhochschulen gelehrt. Seine Erfahrung als Dozent erstreckt sich auf die Ausbildung zukünftiger Ingenieure und Techniker und trägt damit nicht nur zur Weitergabe von Wissen, sondern auch zur Entwicklung des technischen Bereichs bei. Dr. Mevec hat sich hierbei insbesondere auf die Technologie der feuerfesten Werkstoffe an der TU Wien konzentriert. An der Montanuniversität Leoben lag der Fokus auf Hochtemperatur-Wärmedämmstoffen. Internationale Konferenzen und Colloquien haben Dr. Mevec um den Erdball reisen lassen. So durfte er Vorträge nicht nur in Österreich absolvieren, sondern auch in Deutschland, Ungarn, Polen, Rumänien, England, USA, Südafrika, Indien, Thailand und China. Seit einigen Jahren unterrichtet Dr. Mevec nun auch an einer österreichischen HTL im Bemühen, seine Erfahrungen weiter zu geben.",
                "research-title": "Forschung, Materialentwicklung und Kundenbetreuung weltweit",
                "research-text": "Die Arbeit von Dr. Mevec zeichnet sich durch seine internationale Ausrichtung aus. Er hat Forschungsprojekte geleitet und Unterstützung auf vier Kontinenten geleistet, neue Materialien entwickelt und Kunden in einer Vielzahl von Branchen unterstützt. Sein globales Netzwerk und seine interdisziplinären Projekte machen ihn zu einem Experten auf höchstem Niveau. Seine Arbeiten beginnen immer damit, dem Kunden und möglichem Anwender zuzuhören; ganz nach dem Motto: „Geht nicht, gibt’s nicht“. Lösungen für aktuelle schwierige Herausforderungen lassen sich oftmals nicht durch einen Werkstoffwechsel finden. Man muss das System als Ganzes betrachten und konstruktiv querdenken. In Zusammenarbeit mit anerkannten Instituten und Universitäten in Europa und den USA wurden neue Materialien entwickelt und auf kundenspezifischen Anwendungen hin optimiert. Mehr als 70 Länder hat Dr. Mevec beruflich bereist und kleine Firmen sowie globale Konzerne vor Ort beraten und beliefert. ",
                "founding-title": "Gründung eines Ingenieurbüros",
                "founding-text": "Im Jahr 2020 gründete Dr. Mevec sein eigenes Ingenieurbüro mit dem Ziel, Unternehmen und Organisationen in den Bereichen Forschung, Entwicklung und Anwendung von Materialien zu beraten. Seine umfangreiche Erfahrung und Fähigkeit, innovative Lösungen zu finden, machen ihn zu einem gefragten Berater und Partner für Unternehmen auf der ganzen Welt. Seine aktuellen Tätigkeiten liegen im Bereich feuerfester Werkstoffe, anorganischer Fasern und Filamente, der Glasproduktion sowie im Bereich der Hochtemperatur-Recyclingprozesse. ",
                "faq-1": "Welche Dienstleistungen bietet Mevec Consulting an?",
                "faq-1-text": "Mevec Consulting ist auf Materialentwicklung und innovative Lösungen spezialisiert. Wir bieten Beratung in den Bereichen Materialwissenschaft, Prozessoptimierung und maßgeschneiderte Ingenieurlösungen für Ihre Projektanforderungen.",
                "faq-2": "Wie kann ich eine Beratung bei Dr. Gernot Mevec buchen?",
                "faq-2-text": "Sie können eine Beratung buchen, indem Sie das Kontaktformular ausfüllen, unser Büro anrufen oder eine E-Mail an contact@mevec.net senden. Wir werden uns so schnell wie möglich bei Ihnen melden, um einen Termin zu vereinbaren.",
                "faq-3": "Wie schnell kann ich nach der Kontaktaufnahme mit Mevec Consulting mit einer Antwort rechnen?",
                "faq-3-text": "Wir bemühen uns, alle Anfragen innerhalb von 2-3 Werktagen zu beantworten. Wenn Ihre Anfrage dringend ist, rufen Sie uns bitte direkt an.",
                "faq-4": "Bietet Dr. Mevec und sein Team Dienstleistungen nur in Österreich oder auch im Ausland an?",
                "faq-4-text": "Dr. Mevec ist viel gereist und bietet seine Dienstleistungen weltweit an.",
                "faq-5": "Bietet Dr. Mevec analytische Dienstleistungen innerhalb seines Unternehmens an?",
                "faq-5-text": "Das Ingenieurbüro Dr. Gernot Mevec Consulting in Österreich verfügt über kein eigenes Labor. Dr. Mevec kann Sie jedoch an die entsprechenden analytischen Labore verweisen oder die notwendigen analytischen Arbeiten für Sie koordinieren und verwalten.",
                "faq-6": "Bietet Dr. Mevec Dienstleistungen im Bereich Feuerfesttechnik an?",
                "faq-6-text": "Dr. Mevec bietet keine Dienstleistungen im Bereich Feuerfesttechnik an. Das Büro ist jedoch gut vernetzt und kann Sie an ein geeignetes unabhängiges Dienstleistungsunternehmen verweisen.",
                "faq-7": "Bietet Dr. Mevec Unterstützung und Service bei Feuerfestschäden an?",
                "faq-7-text": "Ein klarer Schwerpunkt der Ingenieurdienstleistungen liegt auf der Analyse von Feuerfestschäden. Feuerfestschäden können ein sehr kniffliges Thema sein. Oft findet man nur sehr wenige Beweise oder Belege, daher ist es eine Detektivarbeit. Eine Herausforderung für das Team von Dr. Mevec.",
                "faq-8": "Was sind die ersten Schritte vor Ort, wenn ein Problem auftritt?",
                "faq-8-text": "Um das Rätsel eines Feuerfestschadens zu lösen, muss man wie ein Detektiv vorgehen. Der Schaden sollte gut dokumentiert werden, z.B. durch Fotos und Proben. Daten zu Temperaturen, Atmosphärendruck, pH-Wert, chemischer Zusammensetzung, Staub usw. sollten gesammelt werden.",
                "faq-9": "Wo kann ich Rohstoffe (hauptsächlich anorganische) beziehen?",
                "faq-9-text": "Das Team um Dr. Mevec kann Ihnen Informationen darüber geben, wo Sie Rohstoffe beziehen können, und Sie mit möglichen Lieferanten in Kontakt bringen.",
                "faq-10": "Welche feuerfesten Materialien sind verfügbar?",
                "faq-10-text": "Hochtemperaturanwendungen erfordern verschiedene feuerfeste Materialien; Gießmassen, Ziegel, vorgeformte Teile, Isolierungen, Dichtungen usw. Dr. Mevec und sein Team können Sie bei der Auswahl der richtigen Materialien und Lieferanten unterstützen.",
                "faq-11": "Welche technischen Keramiken eignen sich für Hochtemperaturanwendungen?",
                "faq-11-text": "Hochtemperaturanwendungen erfordern nicht nur feuerfeste Materialien, sondern auch technische Keramiken. Dr. Mevec und sein Team können Sie bei der Auswahl der richtigen Materialien und Lieferanten unterstützen.",
                "faq-12": "Wie kann ich Korrosion in Hochtemperaturprozessen verhindern?",
                "faq-12-text": "Hochtemperaturprozesse führen oft zu korrosiven Gasen und Kondensaten. Daher muss der Ofenmantel so ausgelegt sein, dass er entweder über dem Taupunkt oder weit unter der kritischen Temperatur der Korrosionsschutzbeschichtung betrieben wird. Dr. Mevec und sein Team können Sie in die richtige Richtung weisen.",
                "faq-13": "Wie kann Dr. Mevec bei der Prozessgestaltung helfen?",
                "faq-13-text": "Dr. Mevec und sein Team helfen Ihnen bei der Gestaltung eines Hochtemperaturprozesses und der Überwachung der relevanten Parameter. Eine enge und ordnungsgemäße Überwachung hilft Ihnen, den Betriebsbereich einzugrenzen und Ihre Leistung und Produktivität zu verbessern.",
                "faq-14": "Wie kann ich den Energieverbrauch optimieren?",
                "faq-14-text": "Energie ist ein Schlüsselelement der Kosten. Angesichts der hohen Energiekosten und der starken Kostenschwankungen muss man verstehen, dass Endnutzer eine bessere Isolierung zur Senkung der Gesamtkosten fordern. Eine Verbesserung der Isolierung kann jedoch die Lebensdauer der Feuerfestmaterialien verkürzen. Ein gut ausbalanciertes System sollte entwickelt werden. Das Team von Dr. Mevec hilft Ihnen gerne, Ihr Optimum zu finden.",
                "faq-15": "Wie finde ich den richtigen OEM (Original Equipment Manufacturer)?",
                "faq-15-text": "Europa beherbergt eine Vielzahl gut etablierter OEMs für fast jede Branche und Anwendung. Dr. Mevec und sein Team können Sie bei der Auswahl des richtigen OEM für Ihre Anwendung unterstützen.",
                "faq-16": "Was passiert, wenn das Team von Dr. Mevec den benötigten Service nicht anbieten kann?",
                "faq-16-text": "Wenn das Team von Dr. Mevec den benötigten Service nicht anbieten kann, verweisen wir Sie gerne an andere Industrieexperten in unserem Netzwerk.",
                "created-head":"Diese Website wurde erstellt von:",
                "created-text": "Diese Website wurde von Jakob Hintseiner und Daniel Macek im Rahmen eines Informationstechnologie-Projekts (ITP) an der HTL Waidhofen an der Ybbs im Schuljahr 2024/25 erstellt. Dieses Projekt bot uns eine wertvolle Gelegenheit, das theoretische Wissen, das wir während unserer Ausbildung erworben haben, in einem praktischen, realen Kontext anzuwenden. Unser Ziel war es, eine funktionale, benutzerfreundliche und innovative Lösung zu schaffen. Dies wäre nicht ohne die Unterstützung derjenigen möglich gewesen, die an unsere Vision geglaubt und uns die Möglichkeit gegeben haben, zu wachsen und erfolgreich zu sein."
            }
    };
    const setLanguage = (language) => {
        const elementsToTranslate = document.querySelectorAll("[data-translate]");
        elementsToTranslate.forEach(el => {
            const key = el.getAttribute("data-translate");
            if (langData[language][key]) {
                el.innerHTML = langData[language][key];
            }
        });
    };

    const savedLanguage = localStorage.getItem("lang") || "en";
    setLanguage(savedLanguage);

    document.querySelector("a[href='?lang=en']").addEventListener("click", (e) => {
        e.preventDefault();
        localStorage.setItem("lang", "en");
        setLanguage("en");
    });

    document.querySelector("a[href='?lang=de']").addEventListener("click", (e) => {
        e.preventDefault();
        localStorage.setItem("lang", "de");
        setLanguage("de");
    });
});